import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by me",
};

export default function Gallery() {
    return <div className="font-mono text-black">Gallery in progress</div>;
  }