import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "WSM",
  description: "Generated by me",
};

export default function WSM() {
    return <div>Wandas art page in progress</div>;
  }
