import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by me",
};

export default function Blog() {
  return <div>Blog page in progress</div>;
}