name: Deploy jpurg.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@your_droplet_ip << 'EOF'
            cd /path/to/your/app
            git pull origin main
            npm install
            npm run build
            pm2 restart your-app-name
          EOF
